name: my_schedules
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.1+1
  
  stacked_services: ^1.3.0
  http: any
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^1.5.1
  build_runner: any

flutter:
  uses-material-design: true
